### ISSUE TITLE
分享使用的时候shareListener要怎样设置呢？

### ISSUE THREAD

**Issue by quanyousheng** [shaohui10086/ShareUtil#12]
分享使用的时候ShareUtil.shareImage(this, SharePlatform.QQ, "http://image.com", shareListener);中的shareListener参数之前要怎样设置呢？

**Comment by shaohui10086** [comment]
抱歉，没有看懂你问题所在，直接new一个ShareListener都可以啊。

如果你想问的是：全局设置ShareListener，你可以直接在`Application`中加一个静态成员变量ShareListener，这样每次用的时候都用这一个ShareListener

**Comment by quanyousheng** [comment]
不好意思  我的问题是 分享的时候使用方法：ShareUtil.shareImage(this, SharePlatform.QQ, "http://image.com", shareListener);其中参数shareListener怎么设置文档没有说，所以我有点疑惑

**Comment by shaohui10086** [comment]
直接new就好
