### ISSUE TITLE
支持一下

### ISSUE THREAD

**Issue by tianzhijiexian** [shaohui10086/ShareUtil#2]
想问下这个库和shareloginlib的不同点，然后希望可以一同交流一下坑。我qq：460412008

**Comment by shaohui10086** [comment]
首先说句谢谢，因为从ShareLoginLib学到了很多ヽ(^o^)丿。
其实算起来ShareUtil跟原作算是比较类似的，都是封装了SDK的调用，如果非要说点不一样的：
1. 将代码从Activity中移出，这样看起来更方便些，逻辑更清晰，调用方式统一。
2. 增加一个类似ImageHolder的类，这样就能既支持本地图片分享，也支持图片链接分享，而且分享的图片如果原本是在cache目录下中会被拷贝到public区域，这样别的应用也就能能读到
3. 用Activity-alias转移了WxEntryActivity的位置，没有用Annotation的方式，想使用方尽量简单
4. 同样用manifestPlaceholders,省去了Manifest文件的配置

踩的坑也有很多，我也希望能够交流一下：
1. WxEntryActivity设置了SingleTask，但是微信的回调还是发生在了`onCreate` 方法里，没有发生在onNewIntent中，这个处理起来有些小麻烦
2. 还是微信，分享图片会导致内存泄露，虽然只是泄露的_ShareActivity，也不算很大，只有4Kb左右，但还是有些不爽的，目前在着力解决这个问题

因为测试的并不算太全面，所以暂时遇到的坑就这些，希望多多交流(oﾟ▽ﾟ)o
