### ISSUE TITLE
嗯，十分感谢，很好

### ISSUE THREAD

**Issue by cowthan** [shaohui10086/ShareUtil#3]
very good，确实是第三方登录分享的轻量化可掌控的替代物
我用我们的包名和keystore测了一遍，都通了
同学们刚拉下代码可能需要多配置几个地方，我跟领导商量一下，看能否把我们一个
小项目的包名和keystore && QQ微信微博的key贡献出来
虽然ShareSDK暂时不能替换下来，不过还是要吐下槽，代码都TM混淆了
给楼主点个赞

**Comment by shaohui10086** [comment]
感谢分享！
