### ISSUE TITLE
gradle无法构建

### ISSUE THREAD

**Issue by fandf1990** [shaohui10086/ShareUtil#4]
按使用步骤添加配置后，构建失败，提示内容如下：
Error:(47, 13) Failed to resolve: me.shaohui:shareutil:1.3.5

开发环境：AndroidStudio 2.3 Beta1
Gradle：3.2
Maven仓库：jcenter、https://jitpack.io

**Comment by shaohui10086** [comment]
好像是之前发布失败了，现在重新发布了一下，你再试一下，应该可以了
