### ISSUE TITLE
怎么compile不下来？

### ISSUE THREAD

**Issue by lmz1993** [shaohui10086/ShareUtil#6]
Error:Could not find me.shaohui:shareutil:1.3.5.
Required by:
    fonian:buddhidmapp:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by shaohui10086** [comment]
抱歉，之前的错误导致的，用下面这个，README等会我也更新一下
```
compile 'me.shaohui.shareutil:shareutil:1.3.5'
```

**Comment by lmz1993** [comment]
compile 这个nojar  compile 'me.shaohui.shareutil:shareutil:1.3.5.no_jar'
报错如下：为啥啊？

Error:Execution failed for task ':buddhidmapp:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
	is also present at [me.shaohui.shareutil:shareutil:1.3.5.no_jar] AndroidManifest.xml:27:13-63 value=(orientation|keyboardHidden).
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
	Suggestion: add 'tools:replace="android:configChanges"' to <activity> element at AndroidManifest.xml:191:9-194:75 to override.
:buddhidmapp:processDebugManifest FAILED
Error:screenSize) from AndroidManifest.xml:193:13-74

**Comment by shaohui10086** [comment]
检查一下你的`AndroidManifest`文件，是不是之前自己添加过微博或者QQ分享所需要的Activity，是不是和这里面有重复，[Manifest](https://github.com/shaohui10086/ShareUtil/blob/master/shareutil/src/main/AndroidManifest.xml)，把重复的删掉，如果有什么疑问，可以看下我的这篇文章，关于Manifest文件合并的。[传送门](http://shaohui.me/2016/12/10/three_thing_about_aar_manifest_activity-alias/)
