### ISSUE TITLE
 auth faild

### ISSUE THREAD

**Issue by SeaMyC** [shaohui10086/ShareUtil#9]
按照正常操作，登录弹出授权页面的时候，toast：找不到文件。分享的时候报错误:java.lang.Exception: auth faild!!!!

**Comment by shaohui10086** [comment]
是什么登录? QQ还是微信还是微博？

**Comment by SeaMyC** [comment]
微博登录

**Comment by shaohui10086** [comment]
包名和ID匹配吗？检查一下配置

**Comment by SeaMyC** [comment]
ShareConfig config = ShareConfig.instance()
                .weiboId("971233761")
                .weiboRedirectUrl("https://api.weibo.com/oauth2/default.html");
        //下面是微博登录
        ShareManager.init(config);


这样的初始化 应该可以了吧？

**Comment by SeaMyC** [comment]
ShareConfig config = ShareConfig.instance()
                .weiboId("9712****")
                .weiboRedirectUrl("https://api.weibo.com/oauth2/default.html");
        //下面是微博登录
        ShareManager.init(config);

**Comment by shaohui10086** [comment]
修改一下...把id屏蔽掉

**Comment by shaohui10086** [comment]
你在微博开放平台上设置RedirectUrl了吗？检查一下：包名问题，签名问题，授权回调

**Comment by SeaMyC** [comment]
应用要审核过了 之后才可以 授权登录和分享？

**Comment by shaohui10086** [comment]
对的，，，不然你没办法设置RedirectUrl吧

**Comment by SeaMyC** [comment]
按道理  添加了 测试账号 就可以测试分享功能了呀。

**Comment by SeaMyC** [comment]
我添加的是测试账号，只要知道微博的key就行了，跟包名、签名没关系

**Comment by SeaMyC** [comment]
授权回调  也是写官方推荐回调地址。

**Comment by shaohui10086** [comment]
那就不知道了，我没用过微博的测试账号，直接就是审核通过了的，你可以先用按照微博官方配置走一遍，看能不能跑通

**Comment by SeaMyC** [comment]
建议你去新浪开放平台看一看，不是微博的测试账号，只是给指定的账号测试功能。

**Comment by shaohui10086** [comment]
你测试过能用了吗

**Comment by SeaMyC** [comment]
问题都没解决就closed issues？？

**Comment by SeaMyC** [comment]
问题解决了。 代码放了两天，然后就可以。。。。。。。。

**Comment by shaohui10086** [comment]
你不回我话，我也不知道你解决没啊，我一直想努力积极跟进啊。

还有就是，`ShareUtil`做的工作就是根据你的配置调用目标SDK，然后根据你在第三方应用内的操作（分享或者授权登录），将结果交给第三方SDK处理，并最后将结果进行封装或者进一步操作（比如登录授权成功以后获取用户信息）并返回给设定好的回调。

整个流程分析完成之后，我们分析具体问题：
你在配置好之后，调用微博的分享和登录授权，成功打开了微博的页面，到此为止，`ShareUtil`已经成功完成了它的前一半使命：根据你的配置调用目的SDK，具体你配置的对错，以及微博页面的处理，这些已经不再`ShareUtil`的考虑范围之内了，也不是它所能控制的，剩下就是目的SDK的操作。

在具体到你说到的微博审核没有通过，但是测试账号是可以用的，这点，我是没有操作过，也没办法下评判或者给出任何帮助，但我在积极配合你解决问题。

总之，开心就好:）

**Comment by shaohui10086** [comment]
可以了之后，你没有告诉我。。。

**Comment by SeaMyC** [comment]
刚刚可以的。。。我也不想- -..

**Comment by shaohui10086** [comment]
解决了就好\(^o^)/
